name: Git AntiVirus Scan

on: [push]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
    - uses: actions/checkout@v4
    - name: Git AntiVirus Scan
      uses: djdefi/gitavscan@main
